config/routes.rb
Easyjobs::Application.routes.draw do
  resources :jobs

  root :to => 'jobs#index'

end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render action: 'show', status: :created, location: @job }
      else
        format.html { render action: 'new' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:company_name, :company_website, :company_logo, :job_title, :job_type, :job_category, :job_salary, :job_tags, :job_location, :job_description, :job_apply)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.haml
= form_for @job do |f|
  - if @job.errors.any?
    #error_explanation
      %h2= "#{pluralize(@job.errors.count, "error")} prohibited this job from being saved:"
      %ul
        - @job.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :company_name
    = f.text_field :company_name
  .field
    = f.label :company_website
    = f.text_field :company_website
  .field
    = f.label :company_logo
    = f.text_field :company_logo
  .field
    = f.label :job_title
    = f.text_field :job_title
  .field
    = f.label :job_type
    = f.text_field :job_type
  .field
    = f.label :job_category
    = f.text_field :job_category
  .field
    = f.label :job_salary
    = f.text_field :job_salary
  .field
    = f.label :job_tags
    = f.text_field :job_tags
  .field
    = f.label :job_location
    = f.text_field :job_location
  .field
    = f.label :job_description
    = f.text_area :job_description
  .field
    = f.label :job_apply
    = f.text_area :job_apply
  .actions
    = f.submit 'Save'

app/views/jobs/edit.html.haml
%h1 Editing job

= render 'form'

= link_to 'Show', @job
\|
= link_to 'Back', jobs_path

app/views/jobs/index.html.haml
%h1 Listing jobs

%table
  %tr
    %th Company name
    %th Company website
    %th Company logo
    %th Job title
    %th Job type
    %th Job category
    %th Job salary
    %th Job tags
    %th Job location
    %th Job description
    %th Job apply
    %th
    %th
    %th

  - @jobs.each do |job|
    %tr
      %td= job.company_name
      %td= job.company_website
      %td= job.company_logo
      %td= job.job_title
      %td= job.job_type
      %td= job.job_category
      %td= job.job_salary
      %td= job.job_tags
      %td= job.job_location
      %td= job.job_description
      %td= job.job_apply
      %td= link_to 'Show', job
      %td= link_to 'Edit', edit_job_path(job)
      %td= link_to 'Destroy', job, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Job', new_job_path

app/views/jobs/new.html.haml
%h1 New job

= render 'form'

= link_to 'Back', jobs_path

app/views/jobs/show.html.haml
%p#notice= notice

%p
  %b Company name:
  = @job.company_name
%p
  %b Company website:
  = @job.company_website
%p
  %b Company logo:
  = @job.company_logo
%p
  %b Job title:
  = @job.job_title
%p
  %b Job type:
  = @job.job_type
%p
  %b Job category:
  = @job.job_category
%p
  %b Job salary:
  = @job.job_salary
%p
  %b Job tags:
  = @job.job_tags
%p
  %b Job location:
  = @job.job_location
%p
  %b Job description:
  = @job.job_description
%p
  %b Job apply:
  = @job.job_apply

= link_to 'Edit', edit_job_path(@job)
\|
= link_to 'Back', jobs_path

app/views/layouts/application.html.haml
!!! 5
%html
	%head
		%title Easyjobs
		= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
		= javascript_include_tag "application", "data-turbolinks-track" => true
		= csrf_meta_tags

	%body

		= yield